### ISSUE TITLE
LlewellynMedia -- namespace / nuget not found

### ISSUE THREAD

**Issue by matneyx** [Mavichist/Fountain#2]
I am unable to build the project because the namespace LlewellynMedia isn't available.

**Comment by alekratz** [comment]
Seconded. After numerous, specific Google searches, this set of libraries simply seems to not exist. @Mavichist, help?

**Comment by Mavichist** [comment]
Ah - sorry about that guys. They're inside the Fountain_Windows.zip file in my first release.

**Comment by DrakeShady** [comment]
In visual studio, they are easily imported into the project. However, be sure not to include that part of the project when committing changes.

**Comment by Mavichist** [comment]
It's now included under Fountain/bin/Release.
